#!/usr/bin/env python3
"""生成画像を、ローカルの「プレフィックス (M)」形式へ変更する。

このスクリプトは安全のため、次のルールで動作する。

* flatten_output.sh後の画像、またはRUNフォルダから直接コピーした画像を対象にする
* 既存の「プレフィックス (1)」画像がある場合だけ処理する
* 新しいプレフィックスやマスター未確認のプレフィックスは警告して変更しない
* 拡張子に関係なく、現在の最大番号の次から連番を付ける
* 既存ファイルを上書きしない

使用方法:

1. このファイルを画像フォルダへコピーする。
2. ZIPを展開し、flatten_output.shでまとめた画像を同じフォルダへ置く。
3. 画像フォルダ内で次を実行する。

       python rename_downloads.py

変更内容を確認するだけの場合:

       python rename_downloads.py --dry-run
"""

from __future__ import annotations

import argparse
import re
import sys
import uuid
from dataclasses import dataclass
from pathlib import Path


IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

# Generated output normally has one of these forms:
#   <RUN_ID>__<source_stem>_p001_00001_.png  (after flatten_output.sh)
#   <source_stem>_p001_00001_.png           (directly copied from a run folder)
# RUN_ID is generated by run_batch.sh as YYYYMMDD_HHMMSS.
GENERATED_NAME_RE = re.compile(
    r"^(?:(?P<run_id>\d{8}_\d{6})__)?(?P<source>.+)_p\d+_\d+_$",
    re.IGNORECASE,
)

# Existing local files use: prefix (M).jpg/png/etc.
LOCAL_NAME_RE = re.compile(
    r"^(?P<prefix>.+) \((?P<number>\d+)\)$",
    re.IGNORECASE,
)

# Input stems can already contain a local sequence, for example
# "riri7 (3)". Remove that sequence before looking up the prefix.
SOURCE_SEQUENCE_RE = re.compile(r"\s+\(\d+\)$")


@dataclass(frozen=True)
class ExistingImage:
    path: Path
    prefix: str
    number: int


@dataclass(frozen=True)
class RenamePlan:
    source: Path
    target: Path
    prefix: str
    number: int


def normalize_prefix(value: str) -> str:
    """Return the local prefix with a trailing local sequence removed."""

    return SOURCE_SEQUENCE_RE.sub("", value).strip()


def prefix_key(value: str) -> str:
    """Use Windows-like case-insensitive matching for prefix comparisons."""

    return value.casefold()


def is_image(path: Path) -> bool:
    return path.is_file() and path.suffix.casefold() in IMAGE_EXTENSIONS


def parse_generated_candidate(path: Path) -> str | None:
    """Extract the source prefix from a generated output filename."""

    if not is_image(path):
        return None

    match = GENERATED_NAME_RE.fullmatch(path.stem)
    if match is None:
        return None

    source_prefix = normalize_prefix(match.group("source"))
    return source_prefix or None


def parse_existing_image(path: Path) -> ExistingImage | None:
    """Parse an existing file in the local ``prefix (M)`` convention."""

    if not is_image(path):
        return None

    match = LOCAL_NAME_RE.fullmatch(path.stem)
    if match is None:
        return None

    prefix = match.group("prefix").strip()
    if not prefix:
        return None

    return ExistingImage(
        path=path,
        prefix=prefix,
        number=int(match.group("number")),
    )


def collect_existing_images(directory: Path) -> dict[str, list[ExistingImage]]:
    groups: dict[str, list[ExistingImage]] = {}

    for path in directory.iterdir():
        parsed = parse_existing_image(path)
        if parsed is None:
            continue
        groups.setdefault(prefix_key(parsed.prefix), []).append(parsed)

    return groups


def collect_candidates(directory: Path) -> list[tuple[Path, str]]:
    candidates: list[tuple[Path, str]] = []

    for path in directory.iterdir():
        prefix = parse_generated_candidate(path)
        if prefix is not None:
            candidates.append((path, prefix))

    return sorted(candidates, key=lambda item: item[0].name.casefold())


def canonical_prefix(existing: list[ExistingImage]) -> str | None:
    """Return the spelling used by the existing master, if it is unambiguous."""

    masters = [item for item in existing if item.number == 1]
    if len(masters) != 1:
        return None
    return masters[0].prefix


def build_plan(
    directory: Path,
    candidates: list[tuple[Path, str]],
    existing_groups: dict[str, list[ExistingImage]],
) -> tuple[list[RenamePlan], list[str]]:
    plans: list[RenamePlan] = []
    warnings: list[str] = []
    next_numbers: dict[str, int] = {}
    warned_keys: set[str] = set()
    reserved_names: set[str] = {
        path.name.casefold() for path in directory.iterdir()
    }

    for source, source_prefix in candidates:
        key = prefix_key(source_prefix)
        existing = existing_groups.get(key, [])
        master_prefix = canonical_prefix(existing)

        if master_prefix is None:
            if key not in warned_keys:
                if not existing:
                    warnings.append(
                        f"{source_prefix}: マスター画像 "
                        f"{source_prefix} (1) がないためスキップします。"
                    )
                else:
                    warnings.append(
                        f"{source_prefix}: マスター画像 "
                        f"{source_prefix} (1) が一意に確認できないためスキップします。"
                    )
                warned_keys.add(key)
            continue

        if key not in next_numbers:
            next_numbers[key] = max(item.number for item in existing) + 1

        number = next_numbers[key]
        next_numbers[key] += 1
        target = directory / f"{master_prefix} ({number}){source.suffix}"
        target_key = target.name.casefold()

        if target_key in reserved_names:
            warnings.append(
                f"{source.name}: 変更先 {target.name} が既に存在するため、"
                "このプレフィックスをスキップします。"
            )
            warned_keys.add(key)
            continue

        reserved_names.add(target_key)
        plans.append(
            RenamePlan(
                source=source,
                target=target,
                prefix=master_prefix,
                number=number,
            )
        )

    # A collision warning must not leave a partially planned group behind.
    invalid_keys = {
        prefix_key(plan.prefix)
        for plan in plans
        if prefix_key(plan.prefix) in warned_keys
    }
    plans = [plan for plan in plans if prefix_key(plan.prefix) not in invalid_keys]
    return plans, warnings


def print_plan(plans: list[RenamePlan]) -> None:
    if not plans:
        print("リネーム対象はありません。")
        return

    print("リネーム計画:")
    for plan in plans:
        print(f"  {plan.source.name} -> {plan.target.name}")


def execute_plan(plans: list[RenamePlan]) -> None:
    """Apply the plan through temporary names, without overwriting files."""

    staged: list[tuple[Path, Path, Path]] = []
    completed: list[tuple[Path, Path, Path]] = []

    try:
        for index, plan in enumerate(plans):
            temporary = plan.source.with_name(
                f".rename_downloads_tmp_{uuid.uuid4().hex}_{index}{plan.source.suffix}"
            )
            plan.source.rename(temporary)
            staged.append((plan.source, temporary, plan.target))

        for original, temporary, target in staged:
            temporary.rename(target)
            completed.append((original, temporary, target))
    except Exception:
        # Restore files already moved to their final names first.
        for original, _temporary, target in reversed(completed):
            if target.exists() and not original.exists():
                target.rename(original)

        # Restore files which are still under temporary names.
        for original, temporary, _target in reversed(staged):
            if temporary.exists() and not original.exists():
                temporary.rename(original)
        raise


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Flattened Qwen outputをprefix (M)形式へ安全にリネームします。"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="変更せず、リネーム計画と警告だけを表示します。",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    directory = Path(__file__).resolve().parent

    if not directory.is_dir():
        print(f"ERROR: ディレクトリが存在しません: {directory}", file=sys.stderr)
        return 1

    existing_groups = collect_existing_images(directory)
    candidates = collect_candidates(directory)

    if not candidates:
        print("生成画像ファイルは見つかりませんでした。")
        return 0

    plans, warnings = build_plan(directory, candidates, existing_groups)

    for warning in warnings:
        print(f"警告: {warning}", file=sys.stderr)

    print_plan(plans)

    if args.dry_run:
        print("dry-runのため、ファイルは変更していません。")
        return 0

    try:
        execute_plan(plans)
    except Exception as error:
        print(f"ERROR: リネームを中止しました: {error}", file=sys.stderr)
        return 1

    print(f"完了: {len(plans)}個のファイルをリネームしました。")
    if warnings:
        print(f"警告件数: {len(warnings)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
