MODEL_ID="qwen-image-edit-2509"
MODEL_NAME="Qwen Image Edit 2509"
MODEL_USAGE="comfyui"
QWEN_EDIT_VERSION="2509"
DIFFUSION_FILE="qwen_image_edit_2509_fp8_e4m3fn.safetensors"
DIFFUSION_URL="https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_edit_2509_fp8_e4m3fn.safetensors"
DIFFUSION_SHA256="318568f61951ab9da21100c7b896e3c1da67f0d2efad6421545e022cfaa2b2b4"
LORA_FILE="Qwen-Image-Edit-2509-Lightning-4steps-V1.0-bf16.safetensors"
LORA_URL="https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Edit-2509/Qwen-Image-Edit-2509-Lightning-4steps-V1.0-bf16.safetensors"
LORA_SHA256="2a32ce938ec71db2b49a817b4844ae86995569518dea56ee0ddc209cbe8e1377"
WORKFLOW_FILE_NAME="Qwen-Image-Edit-2509-official.json"
WORKFLOW_URL="https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/image_qwen_image_edit_2509.json"
APPROX_TOTAL_BYTES="31000000000"
WORKFLOW_REPLACE_FROM=""
WORKFLOW_REPLACE_TO=""
